export const ClickActions = {

    CAMPAIGN_DETAILS: "CAMPAIGN_DETAILS",

    CAMPAIGN_LIST: "CAMPAIGN_LIST",

    APPLICATION_DETAILS: "APPLICATION_DETAILS",

    DEAL_DETAILS: "DEAL_DETAILS",

    CHAT: "CHAT",

    DEAL: "DEAL",

    PAYMENT: "PAYMENT",

    PROFILE: "PROFILE",

    HOME: "HOME",

    NOTIFICATION: "NOTIFICATION",

    REFERRAL: "REFERRAL",

};
