export const NotificationTypes = {
  // Campaign
  NEW_CAMPAIGN: "NEW_CAMPAIGN",
  CAMPAIGN_UPDATED: "CAMPAIGN_UPDATED",
  CAMPAIGN_CLOSED: "CAMPAIGN_CLOSED",

  // Application
  APPLICATION_RECEIVED: "APPLICATION_RECEIVED",
  APPLICATION_ACCEPTED: "APPLICATION_ACCEPTED",
  APPLICATION_REJECTED: "APPLICATION_REJECTED",

  // Deal
  DEAL_CREATED: "DEAL_CREATED",
  DEAL_UPDATED: "DEAL_UPDATED",
  DEAL_COMPLETED: "DEAL_COMPLETED",

  // Payment
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_RELEASED: "PAYMENT_RELEASED",

  // Chat
  CHAT_MESSAGE: "CHAT_MESSAGE",

  // Admin
  ADMIN_ANNOUNCEMENT: "ADMIN_ANNOUNCEMENT",

  // Referral
  REFERRAL_BONUS: "REFERRAL_BONUS",
};
